version: '3.9'
services:
  db:
    image: mysql:8.0.29
    container_name: mysql_java
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db